"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./AuthProvider";
import React, { Suspense } from 'react'
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { StoreProvider} from '@/redux/StoreProvider'


const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {



  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <AuthProvider>
            <Suspense fallback={<div>Loading...</div>}>
              <Navbar />
                {children}
              <Footer />  
            </Suspense>
          </AuthProvider>
        </StoreProvider>   
      </body>
    </html>
  );
}
