"use client"

import "./globals.css";
import AuthProvider from "./AuthProvider";
import ClientProviders from './ClientProviders';
import React, { Suspense } from 'react'
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { StoreProvider} from '@/redux/StoreProvider'


// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children, session  }) {



  return (
    <html lang="en">
      <body className={`antialiased`}>
        <StoreProvider>
          <AuthProvider session={session}>
            <Suspense fallback={<div>Loading...</div>}>
              <Navbar />
                {children}
              <Footer />  
            </Suspense>
          </AuthProvider>
        </StoreProvider>   
      </body>
    </html>
  );
}
